### ISSUE TITLE
Plans for multiple amplicons per barcode?

### ISSUE THREAD

**Issue by Kirk3gaard** [epi2me-labs/wf-amplicon#11]
### Is your feature related to a problem?

Most people doing environmental samples do amplicon sequencing for mixed communities so it would be convenient to have a solution for handling this kind of data.

https://x.com/kirk3gaard/status/1750126916152021098?s=20

### Describe the solution you'd like

A QIIME/Mothur/USEARCH/DADA2 equivalent for nanopore data.

### Describe alternatives you've considered

Some good ideas were mentioned in the replies to this tweet. QIIME/Mothur/USEARCH

**Comment by julibeg** [comment]
Hi @Kirk3gaard!

Thank you for the feature request. This is on the list of things we would like to include in the workflow, but I cannot give you timelines (or even guarantee that it is going to be included here; it might, for example, be decided to expand the capabilities of [wf-16s](https://www.youtube.com/watch?v=m8iqsTtglGQ&t) instead).

If you have a database / reference for your community, you can already use wf-16s to analyse your data (this won't do _de novo_ clustering or similar though).

Regarding the points raised in the linked thread: As noted there, Q28 was achieved and Q30 is within reach. DADA2 needs [10% or more error-free reads](https://github.com/benjjneb/dada2/issues/759#issuecomment-491790101) in order for the denoising to work. For a 1500 bp gene (e.g. 16S) this would require Q28 or above. This means that full-length 16S ASVs from ONT reads would be possible (which is very exciting).

However, as noted during the last [ONT Update](https://www.youtube.com/watch?v=m8iqsTtglGQ&t) at NCM Houston, these improved conditions + basecallers are still under active development. We will revisit the question of DADA2 once they become available.

**Comment by julibeg** [comment]
Closing for now
