### ISSUE TITLE
when will wf-amplicon be updated to use dna_r10.4.1_e8.2_400bps_sup@v4.3.0?

### ISSUE THREAD

**Issue by ChristopherRichie** [epi2me-labs/wf-amplicon#17]
### Ask away!

is there a schedule for making downstream workflows compatiable and up to date with the latest basecaller?
thanks

**Comment by cjw85** [comment]
We're in the process of updating all our workflows with a complete list of all the latest basecallers. This will also change the workflows to default to introspecting the input files to automatically detect the basecaller used.

**Comment by julibeg** [comment]
hi @ChristopherRichie, the most recent release v1.1.1 can handle the latest basecall models. Thank you for your patience!
