### ISSUE TITLE
(Singularty) Container missing python

### ISSUE THREAD

**Issue by marchoeppner** [epi2me-labs/wf-amplicon#20]
### Operating System

Other Linux (please specify below)

### Other Linux

AlmaLinux 9.4

### Workflow Version

v1.1.1

### Workflow Execution

Command line (Cluster)

### CLI command run

nextflow run epi2me-labs/wf-amplicon --fastq reads.fastq.gz --reference  /work_syn/shared/references/foodme2/1.0/databases/co1/co1.fasta -profile singularity

### Workflow Execution - CLI Execution Profile

Singularity

### What happened?

When running release 1.1.1 using the singularity profile, the process `pipeline:getVersions` fails due to python being absent from the container. 

Container used: docker://ontresearch/wf-common:sha8b5843d549bb210558cbb676fe537a153ce771d6

```bash
singularity exec /work_syn/ngs/pipelines/foodme2/ont/epi2me/work/singularity/ontresearch-wf-amplicon-sha79b5ac4013195fec9809f2b71ef55b87bf9c7f16.img which python
```
Returns: nothing

``` 
singularity exec /work_syn/ngs/pipelines/foodme2/ont/epi2me/work/singularity/ontresearch-wf-amplicon-sha79b5ac4013195fec9809f2b71ef55b87bf9c7f16.img which perl
``` 
Returns: /usr/bin/perl

I see that you borrowed some stuff from nf-core - there is some documentation available on how to run a minimal pipeline test as part of the pre-release checks (for example: https://github.com/nf-core/sarek/blob/master/.github/workflows/download_pipeline.yml). Probably useful to set something like that up here also.  

### Relevant log output

```shell
ERROR ~ Error executing process > 'pipeline:getVersions'

Caused by:
  Process `pipeline:getVersions` terminated with an error exit status (127)


Command executed:

  python --version | tr ' ' ',' | sed 's/P/p/' > versions.txt
  fastcat --version | sed 's/^/fastcat,/' >> versions.txt
  python -c "import ezcharts; print(f'ezcharts,{ezcharts.__version__}')" >> versions.txt
  python -c "import dominate; print(f'dominate,{dominate.__version__}')" >> versions.txt
  python -c "import numpy; print(f'numpy,{numpy.__version__}')" >> versions.txt
  python -c "import pandas; print(f'pandas,{pandas.__version__}')" >> versions.txt
  python -c "import pysam; print(f'pysam,{pysam.__version__}')" >> versions.txt
  python -c "import si_prefix; print(f'si-prefix,{si_prefix.__version__}')" >> versions.txt
  seqkit version | tr ' ' ',' >> versions.txt
  printf "porechop,%s\n" $(porechop --version) >> versions.txt
  samtools --version | head -n1 | tr ' ' ',' >> versions.txt
  printf "minimap2,%s\n" $(minimap2 --version) >> versions.txt
  mosdepth --version | tr ' ' ',' >> versions.txt
  printf "miniasm,%s\n" $(miniasm -V) >> versions.txt
  printf "racon,%s\n" $(racon --version) >> versions.txt
  printf "csvtk,%s\n" $(csvtk version | grep -oP '\d+\.\d+.\d+') >> versions.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: python: command not found
```

### Were you able to successfully run the latest version of the workflow with the demo data?

other (please describe below)

### Other demo data information

```shell
Not an issue with the data, obviously.
```

**Comment by SamStudio8** [comment]
Hi @marchoeppner,
Thanks again for taking the time to file an issue with us, I've addressed your comment on one of our other workflows, see https://github.com/epi2me-labs/wf-16s/issues/21#issuecomment-2228177293.

**Comment by marchoeppner** [comment]
Yes, solved in the other thread.
