### ISSUE TITLE
Apptainer instead of singulaity

### ISSUE THREAD

**Issue by passelma42** [epi2me-labs/wf-amplicon#24]
### Ask away!

Is it possible to run the wf in apptainer or will it be modified soon? Our HPC cluster still supports singularity but is moving towards apptainer.

**Comment by SamStudio8** [comment]
We have not tested with Apptainer so do not support it directly, but it shares many similarities with Singularity and you may find the Singularity profile still works. The Nextflow community might be able to help more with questions about support for Apptainer.
