### ISSUE TITLE
Cannot use more then 4 cores with nextflow. 

### ISSUE THREAD

**Issue by nfbourg** [epi2me-labs/wf-amplicon#3]
### Operating System

Other Linux (please specify below)

### Other Linux

RedHat

### Workflow Version

0.2.3-g5e5a866

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-amplicon --fastq [fastq_dir]  --reference [reference_file] --threads 20 -profile singularity

### Workflow Execution - CLI Execution Profile

None

### What happened?

I receive the Error

"
ERROR ~ Error executing process > 'pipeline:porechop (1)'

Caused by:
  Process requirement exceeds available CPUs -- req: 5; avail: 4
"

### Relevant log output

```shell
ERROR ~ Error executing process > 'pipeline:porechop (1)'

Caused by:
  Process requirement exceeds available CPUs -- req: 5; avail: 4
```

**Comment by julibeg** [comment]
Hi there!

The number of CPUs available to Nextflow in a local execution context is governed by `executor.$local.cpus` in the Nextflow configuration. The default for wf-amplicon is 4 CPUs. If you want to use more (e.g. 20 in your example), please override the setting with a local config. This would work as follows:
```shell
# in `local.config`
executor {
    $local {
        cpus = 20
        memory = "16 GB"
    }
}


# then run the workflow with
$ nextflow run epi2me-labs/wf-amplicon \
    -profile singularity \
    -c local.conf \
    --fastq <fastq_dir> \
    --reference <reference_file> \
    --threads 20
```

**Comment by nfbourg** [comment]
I see, Thank you!On Jul 27, 2023, at 4:58 AM, Julian Libiseller-Egger ***@***.***> wrote:﻿
Hi there!
The number of CPUs available to Nextflow in a local execution context is governed by executor.$local.cpus in the nextflow.config. The default maximum for wf-amplicon is 4 CPUs. If you want to use more (e.g. 20 in your example), please either modify nextflow.config accordingly or (and this is the preferred option) override it with a local config. This would work as follows:
# in `local.config`
executor {
    $local {
        cpus = 20
        memory = "16 GB"
    }
}


# then run the workflow with
$ nextflow run epi2me-labs/wf-amplicon \
    -profile singularity \
    -c local.conf \
    --fastq <fastq_dir> \
    --reference <reference_file> \
    --threads 20
