### ISSUE TITLE
cannot find .bai in the output/SampleID/alignment Directory

### ISSUE THREAD

**Issue by apilucky** [epi2me-labs/wf-amplicon#4]
### Ask away!

I want to take the alignment and its index file (bam and bai) out and visualize on IGV but I found only .bam in the output/alignment directory.
Firstly,  I think the workflow does not generate the index file by default but I found the index file under the work/alignRead directory process.  
How can we place them with the corresponding bam file?

**Comment by julibeg** [comment]
Hi @apilucky!

Thanks for bringing this up. The newest version of the workflow (v0.3.5) now also emits the `.bai` files. Please give it a try and close this issue if the newest release resolved it. If not, please let us know!

**Comment by apilucky** [comment]
Thank you for the new update.
I have done an analysis on the updated version. 
It is perfect. :)
