### ISSUE TITLE
Download wf in CMD

### ISSUE THREAD

**Issue by passelma42** [epi2me-labs/wf-amplicon#8]
### Ask away!

Hi, is it possible to download the wf through command line and run it offline? If so, how would I go about?

**Comment by julibeg** [comment]
Hi @passelma42! If you've run the wf to completion once (i.e. the pipeline and docker / singularity images have been pulled), you can run it without internet using the regular CLI command.

Please let us know if you're running into any issues.

**Comment by passelma42** [comment]
Hi Julian,

Thanks.
So I'll need to run it in the same working directory to where the singularity folder/images are pulled?

Is it also possible to run it with apptainer? This would be our togo option for running containers on our HPC.
Greets
Pieter

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by julibeg** [comment]
Hi Pieter and sorry for the delay!

>So I'll need to run it in the same working directory to where the singularity folder/images are pulled?

You can set the env variable `NXF_SINGULARITY_CACHEDIR` to tell singularity where to put / look for images. Depending on your HPC environment, some additional setup for running singularity offline might be necessary.

>Is it also possible to run it with apptainer?

Apptainer and Singularity can be used interchangeably. Depending on your Apptainer installation, you might need to create a symlink named `singularity` in a directory somewhere in your $PATH to make it available.

Good luck!
